server:
  port: 7777

spring:
  application:
    name: Mpesa-darajaApi

  datasource:
    url: jdbc:mysql://localhost:3306/darajadb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

mpesa:
  daraja:
    consumer-key: Ak5AMVeouOea80OFFEp8qRGushwedEmFop8mXjKfw3OHwA4t
    consumer-secret: OWLDtNFP1DWMBvpcZSCyI0HkT0t9CVzKK3TQqT7ivSDnAE1f1zRVut5pp1GiAlRe
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    grant_type: client_credentials

    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    shortCode: 600426
    confirmationURL: http://localhost:7777/payment/confirmation
    validationURL: http://localhost:7777/payment/validation
    responseType: Completed

    stkPassKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    stkPushShortCode: 174379
    stkPushRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    stkPushRequestCallbackUrl: http://localhost:7777/payment/stk-transaction-result

